stages:
  - build
  - test
  - style

py.test:
  stage: test
  script:
    - pipenv install --dev
    - pipenv run py.test
  except:
    - /^wip\/.*/
    - /^WIP\/.*/
  tags:
    - rapl


flake8:
  stage: style
  script:
    - pipenv install --dev
    - pipenv run flake8
  except:
    - /^wip\/.*/
    - /^WIP\/.*/

nrm.build:
  stage: build
  script:
    - nix-build .nix -A nrm
  tags:
    - integration

libnrm.build:
  stage: build
  script:
    - nix-build .nix -A libnrm
  tags:
    - integration

containers.build:
  stage: build
  script:
    - nix-build .nix -A containers
  tags:
    - integration

helloworld.integration.test:
  stage: test
  script:
    - nix-shell .nix -A test --run "argotk.hs helloworld"
  artifacts:
    paths:
      - _output/cmd_err.log
      - _output/cmd_out.log
      - _output/daemon_out.log
      - _output/daemon_out.log
      - _output/nrm.log
      - _output/.argo_nodeos_config_exit_message
    expire_in: 1 week
  except:
    - /^wip\/.*/
    - /^WIP\/.*/
  tags:
    - integration

perfwrapper.integration.test:
  stage: test
  script:
    - nix-shell .nix -A test --run "argotk.hs perfwrapper"
  artifacts:
    paths:
      - _output/cmd_err.log
      - _output/cmd_out.log
      - _output/daemon_out.log
      - _output/daemon_out.log
      - _output/nrm.log
      - _output/.argo_nodeos_config_exit_message
    expire_in: 1 week
  except:
    - /^wip\/.*/
    - /^WIP\/.*/
  tags:
    - integration
