stages:
  - test
  - style

py.test:
  stage: test
  script:
    - pipenv install --dev
    - pipenv run py.test
  except:
    - /^wip\/.*/
    - /^WIP\/.*/
  tags:
    - rapl


flake8:
  stage: style
  script:
    - pipenv install --dev
    - pipenv run flake8
  except:
    - /^wip\/.*/
    - /^WIP\/.*/

integration.test:
  stage: test
  script:
    - nix-shell .integration.nix --run "argotk.hs helloworld"
  artifacts:
    paths:
      - _output/cmd_err.log
      - _output/cmd_out.log
      - _output/daemon_out.log
      - _output/daemon_out.log
      - _output/nrm.log
      - _output/time.log
      - _output/.argo_nodeos_config_exit_message
    expire_in: 1 week
  except:
    - /^wip\/.*/
    - /^WIP\/.*/
  tags:
    - integration
