variables:
  ARGOPKGS : "https://xgitlab.cels.anl.gov/argo/argopkgs/-/archive/master/argopkgs-master.tar.gz"
  EXTRA : "--nrm ./."

stages:
  - style
  - build
  - test
  - quality

include:
 - https://xgitlab.cels.anl.gov/argo/argopkgs/raw/continuous-integration/gitlab-ci/argonix.yml
 - https://xgitlab.cels.anl.gov/argo/argopkgs/raw/continuous-integration/gitlab-ci/components.yml
 - https://xgitlab.cels.anl.gov/argo/argopkgs/raw/continuous-integration/gitlab-ci/integration.yml
 - https://xgitlab.cels.anl.gov/argo/argopkgs/raw/continuous-integration/gitlab-ci/repoquality.yml

py.test:
  stage: test
  script:
    - pipenv install --dev
    - pipenv run py.test
  tags:
    - rapl

flake8:
  stage: style
  script:
    - pipenv install --dev
    - pipenv run flake8
