include: 'https://xgitlab.cels.anl.gov/argo/argotest/raw/master/gitlab/binary_rename.yml'

stages:
  - style
  - build
  - test

py.test:
  stage: test
  script:
    - pipenv install --dev
    - pipenv run py.test
  tags:
    - rapl

flake8:
  stage: style
  script:
    - pipenv install --dev
    - pipenv run flake8
