include: 'https://xgitlab.cels.anl.gov/argo/argotest/raw/master/gitlab/basic.yml'

variables:
  ARGOPKGS : "https://xgitlab.cels.anl.gov/argo/argopkgs/-/archive/continuous-integration/argopkgs-continuous-integration.tar.gz"

stages:
  - style
  - build
  - test

py.test:
  stage: test
  script:
    - pipenv install --dev
    - pipenv run py.test
  tags:
    - rapl

flake8:
  stage: style
  script:
    - pipenv install --dev
    - pipenv run flake8

repoquality:
  stage: style
  script:
    - nix run -f "$ARGOPKGS" repoquality --command repoquality
  tags:
    - integration
